SUPABASE_URL = "https://mdkqltffmxczbiagdorv.supabase.co"

SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ka3FsdGZmbXhjemJpYWdkb3J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgwNDYzMjQsImV4cCI6MjA5MzYyMjMyNH0.ImjwMex1W4BgcZ89OBGi_lvfHzjJFKkillIoL2bh1Gg"
